config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    member do
      post 'imgsave', to: 'plans#imgsave'
    end
  end


  # devise_for :users
  # devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: {
    :omniauth_callbacks => "omniauth_callbacks",
    sessions:      'users/sessions'
  }

  # get 'users/show'
  get '/users/:username',to: 'users#show', as: 'users_show'
  #get '/users/:id',to: 'users#show', as: 'users_show'
  
  authenticated :user do
    root to: 'users#show'
  end

  root to:  'plans#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan,only: [:show,:edit,:update,:destroy,:imgsave]

  def index
    @plans = Plan.where(desplay: true).order("created_at DESC")
  end

  def show
  end

  def new
    @plan = Plan.new()
  end

  def edit
  end

  def create
    @plan = current_user.plans.new(plan_params)
    if @plan.save
      redirect_to users_show_path(current_user.username), notice: 'LeanCanvasを作成しました'
    else
      render :new
    end
  end

  def update
    if @plan.update(plan_params)
      kit   = IMGKit.new(request.url)
      img   = kit.to_img(:png)
      file  = Tempfile.new(["image_#{@plan.id}", '.png'], 'tmp',:encoding => 'ascii-8bit')
      file.write(img)
      file.flush
      @plan.image = file
      @plan.update(plan_params)
      redirect_to @plan, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @plan.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  def imgsave
    kit   = IMGKit.new(request.referer)
    img   = kit.to_img(:png)
    file  = Tempfile.new(["image_#{@plan.id}", '.png'], 'tmp',:encoding => 'ascii-8bit')
    file.write(img)
    file.flush
    @plan.image = file
    @plan.update(plan_params)
  end

  private
  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:id,:title,:segment,:problem,:valu,:solution,:chanel,:profit,:cost,:parameter,:superiority,:image, :desplay)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<section id="leancanvas_form">
<p class="center">
  <a class="sp_on btn waves-effect waves-light btn-small"><i class="material-icons left">phone_iphone</i>SP表示にする</a>
  </p>
  <p class="center">
    <a class="pc_on btn waves-effect waves-light btn-small teal lighten-3"><i class="material-icons left">laptop_mac</i>PC表示にする</a>
  </p>

  <div class="not_sp">
<%= form_for(@plan) do  |f| %>
  <div class="input-field">
    <%= f.text_field :title, autofocus: true, autocomplete: "title",:tabindex => "1",:required => true %>
    <%= f.label :title, "サービス名（入力必須）" %>
  </div>

<div class="row main_row">
  <div class="area_box col s2">
    <div class="input-field bigbox">
      <%= f.text_area :problem, class: 'materialize-textarea',:tabindex => "2",:placeholder=>"上位3つの課題" ,:required => true %>
      <%= f.label :problem,"課題" %>
      <span class="num">1</span>
    </div>
  </div>

  <div class="area_box col s3">
    <div class="input-field smallbox">
      <%= f.text_area :solution, class: 'materialize-textarea',:tabindex => "5",:placeholder=>"上位3つの機能" ,:required => true %>
      <%= f.label :solution,"ソリューション" %>
      <span class="num">4</span>
    </div>


    <div class="input-field smallbox">
      <%= f.text_area :parameter, class: 'materialize-textarea',:tabindex => "9",:placeholder=>"計測する主要活動" ,:required => true %>
      <%= f.label :parameter,"主要指標" %>
      <span class="num">8</span>
    </div>
  </div>


  <div class="area_box col s2">
    <div class="input-field bigbox">
      <%= f.text_area :valu, class: 'materialize-textarea',:tabindex => "4",:placeholder=>"あなたの差別化要因と注目に値する価値を説明した単一で明確な説得力のあるメッセージ",:required => true  %>
      <%= f.label :valu,"独自の価値提案" %>
      <span class="num">3</span>
    </div>
  </div>

  <div class="area_box col s3">
    <div class="input-field smallbox">
      <%= f.text_area :superiority, class: 'materialize-textarea' ,:tabindex => "10",:placeholder=>"簡単にコピーや購入ができないもの",:required => true  %>
      <%= f.label :superiority,"圧倒的な優位性" %>
      <span class="num">9</span>
    </div>

    <div class="input-field smallbox">
      <%= f.text_area :chanel, class: 'materialize-textarea',:tabindex => "6",:placeholder=>"顧客への経路",:required => true  %>
      <%= f.label :chanel,"チャネル" %>
      <span class="num">5</span>
    </div>
  </div>

  <div class="area_box col s2">
    <div class="input-field bigbox">
      <%= f.text_area :segment, class: 'materialize-textarea',:tabindex => "3",:placeholder=>"ターゲットにする顧客",:required => true  %>
      <%= f.label :segment,"顧客セグメント" %>
      <span class="num">2</span>
    </div>
  </div>
</div>


<div class="row sub_row">
  <div class="col s6 moneybox">
    <div class="input-field">
      <%= f.text_area :cost, class: 'materialize-textarea',:tabindex => "8",:placeholder=>"流通コスト/顧客獲得コスト/ホスティングコスト/人件費など",:required => true  %>
      <%= f.label :cost,"コスト構造" %>
      <span class="num">7</span>
    </div>
  </div>

  <div class="col s6 moneybox">
    <div class="input-field">
      <%= f.text_area :profit, class: 'materialize-textarea',:tabindex => "7",:placeholder=>"収益モデル/収益/顧客生涯価値/粗利益",:required => true  %>
      <%= f.label :profit,"収益の流れ" %>
      <span class="num">6</span>
    </div>
  </div>
</div>

<div class="center">
  <p class="center">
  <%= f.check_box :desplay, {:checked => true, :class => "filled-in"}, "true" ,"false"%>
    <%= f.label :desplay, "公開をしますか", id: 'plan_desplay', for: 'plan_desplay' %>
  </p>
</div>

  <div class="actions center-align btn_block">
    <%= f.submit "追加する", class: 'btn waves-effect waves-light' ,:tabindex => "11",:required => true %>
  </div>

<% end %>
</div>

<div class="sp">
<%= form_for(@plan) do  |f| %>
  <div class="input-field">
    <%= f.text_field :title, autofocus: true, autocomplete: "title",:required => true %>
    <%= f.label :title, "サービス名（入力必須）" %>
  </div>

    <div class="input-field single_block">
      <%= f.text_area :problem, class: 'materialize-textarea sp_textarea',:placeholder=>"上位3つの課題" ,:required => true %>
      <%= f.label :problem,"課題",class: 'sp_label'  %>
    </div>

    <div class="input-field single_block">
      <%= f.text_area :solution, class: 'materialize-textarea sp_textarea',:placeholder=>"上位3つの機能" ,:required => true %>
      <%= f.label :solution,"ソリューション",class: 'sp_label'  %>
    </div>


    <div class="input-field single_block">
      <%= f.text_area :parameter, class: 'materialize-textarea sp_textarea',:placeholder=>"計測する主要活動" ,:required => true %>
      <%= f.label :parameter,"主要指標",class: 'sp_label'  %>
    </div>

    <div class="input-field single_block">
      <%= f.text_area :valu, class: 'materialize-textarea sp_textarea',:placeholder=>"あなたの差別化要因と注目に値する価値を説明した単一で明確な説得力のあるメッセージ",:required => true  %>
      <%= f.label :valu,"独自の価値提案" ,class: 'sp_label' %>
    </div>

    <div class="input-field single_block">
      <%= f.text_area :superiority, class: 'materialize-textarea sp_textarea' ,:placeholder=>"簡単にコピーや購入ができないもの",:required => true  %>
      <%= f.label :superiority,"圧倒的な優位性" ,class: 'sp_label' %>
    </div>

    <div class="input-field single_block">
      <%= f.text_area :chanel, class: 'materialize-textarea sp_textarea',:placeholder=>"顧客への経路",:required => true  %>
      <%= f.label :chanel,"チャネル" ,class: 'sp_label' %>
    </div>

    <div class="input-field single_block">
      <%= f.text_area :segment, class: 'materialize-textarea sp_textarea',:placeholder=>"ターゲットにする顧客",:required => true  %>
      <%= f.label :segment,"顧客セグメント" ,class: 'sp_label' %>
    </div>


    <div class="input-field single_block">
      <%= f.text_area :cost, class: 'materialize-textarea sp_textarea',:placeholder=>"流通コスト/顧客獲得コスト/ホスティングコスト/人件費など",:required => true  %>
      <%= f.label :cost,"コスト構造" ,class: 'sp_label' %>
    </div>

    <div class="input-field single_block">
      <%= f.text_area :profit, class: 'materialize-textarea sp_textarea',:placeholder=>"収益モデル/収益/顧客生涯価値/粗利益",:required => true  %>
      <%= f.label :profit,"収益の流れ" ,class: 'sp_label' %>
    </div>

<div class="center">
  <p class="center">
  <%= f.check_box :desplay, {:checked => true, :class => "filled-in"}, "true" ,"false"%>
    <%= f.label :desplay, "公開をしますか", id: 'plan_desplay', for: 'plan_desplay' %>
  </p>
</div>

  <div class="actions center-align btn_block">
    <%= f.submit "追加する", class: 'btn waves-effect waves-light' ,:required => true %>
  </div>

<% end %>
</div>

</section>
<script>
$(".pc_on").hide();
$(".sp").hide();
$(".sp_on").click(function(){
  $(".not_sp").hide();
  $(".sp").show();
  $(".sp_on").hide();
  $(".pc_on").show();
})

$(".pc_on").click(function(){
  $(".not_sp").show();
  $(".sp").hide();
  $(".sp_on").show();
  $(".pc_on").hide();
})
</script>

app/views/plans/edit.html.erb
<h2 class="center">編集する</h2>

<%= render 'form', plan: @plan %>

app/views/plans/index.html.erb
<h2 class="center">みんなのリーンキャンバス </h2>
<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false" data-text="リーンキャンバスメーカー | Web上でリーンキャンバスを描くことが出来る。10秒でリーンキャンバスを作成しよう。 #リーンキャンバスメーカー">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<div class="fb-like" data-href="http://www.leancanvasmaker.com" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
<div class="row">
<% @plans.each do |plan| %>

  <div class="card small col m6">
    <div class="card-image waves-effect waves-block waves-light">
        <%= image_tag plan.image.url if plan.image.url != nil %>
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><%= plan.title %></span>
      <% if plan.image.url == nil %>
        <p>まだリーンキャンバスの画像がありません。</p>
      <% end %>
      <p><%= link_to "詳細を見る", plan_path(plan) %></p>
    </div>
  </div>
<% end %>
</div>
<%# end %>

app/views/plans/new.html.erb
<h2 class="center">新規作成</h2>

<%= render 'form', plan: @plan %>

app/views/plans/show.html.erb
<section id="leancanvas_show">
    <h3><%= @plan.title%></h3>
    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false" data-text="@<%= @plan.user.username %> さんが 「<%= @plan.title %>」を作成しました。 #LeancanvasMaker">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <div class="fb-like" data-href="http://www.leancanvasmaker.com" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

  <div class="creater">
    <%= link_to users_show_path(@plan.user.username) do %>
    <% if @plan.user.icon? %>
      <i><%= image_tag @plan.user.icon ,class: 'user_img_icon' if @plan.user.icon != nil %></i>
    <% else %>
      <i><%= image_tag @plan.user.image ,class: 'user_img_icon' if @plan.user.image != nil %></i>
    <% end %>
    <%= @plan.user.name %>
  <% end %>
  </div>
  <p class="center">
  <a class="sp_on btn waves-effect waves-light btn-small"><i class="material-icons left">phone_iphone</i>SP表示にする</a>
  </p>
  <p class="center">
    <a class="pc_on btn waves-effect waves-light btn-small teal lighten-3"><i class="material-icons left">laptop_mac</i>PC表示にする</a>
  </p>

<div class="not_sp">
<div class="row main_row">
  <div class="grey lighten-5 area_box col s2">
      <h4>【課題】</h4>
      <%= simple_format(@plan.problem) %>
  </div>
  <div class="grey lighten-5 area_box col s3">
    <div class="smallbox">
      <h4>【ソリューション】</h4>
      <%= simple_format(@plan.solution) %>
    </div>
    <div class="smallbox">
      <h4>【主要指標】</h4>
      <%= simple_format(@plan.parameter) %>
    </div>
  </div>

  <div class="grey lighten-5 area_box col s2">
      <h4>【独自の価値提案】</h4>
      <%= simple_format(@plan.valu) %>
  </div>

  <div class="grey lighten-5 area_box col s3">
    <div class="smallbox">
      <h4>【圧倒的な優位性】</h4>
      <%= simple_format(@plan.superiority) %>
    </div>
    <div class="smallbox">
      <h4>【チャネル】</h4>
      <%= simple_format(@plan.chanel) %>
    </div>
  </div>

  <div class="grey lighten-5 area_box col s2">
      <h4>【顧客セグメント】</h4>
      <%= simple_format(@plan.segment) %>
  </div>
</div>


<div class="row sub_row">
  <div class="col s6 moneybox grey lighten-5">
    <h4>【コスト構造】</h4>
    <%= simple_format(@plan.cost) %>
  </div>
  <div class="col s6 moneybox grey lighten-5">
    <h4>【収益の流れ】</h4>
    <%= simple_format(@plan.profit) %>
  </div>
</div>
</div>


<div class="sp">
  <div class="single_block">
      <h4>【課題】</h4>
      <%= simple_format(@plan.problem) %>
  </div>
  <div class="single_block">
    <h4>【ソリューション】</h4>
    <%= simple_format(@plan.solution) %>
  </div>
  <div class="single_block">
    <h4>【主要指標】</h4>
    <%= simple_format(@plan.parameter) %>
  </div>

  <div class="single_block">
      <h4>【独自の価値提案】</h4>
      <%= simple_format(@plan.valu) %>
  </div>

  <div class="single_block">
    <h4>【圧倒的な優位性】</h4>
    <%= simple_format(@plan.superiority) %>
  </div>
  <div class="single_block">
    <h4>【チャネル】</h4>
    <%= simple_format(@plan.chanel) %>
  </div>

  <div class="single_block">
      <h4>【顧客セグメント】</h4>
      <%= simple_format(@plan.segment) %>
  </div>

  <div class="single_block">
    <h4>【コスト構造】</h4>
    <%= simple_format(@plan.cost) %>
  </div>
  <div class="single_block">
    <h4>【収益の流れ】</h4>
    <%= simple_format(@plan.profit) %>
  </div>
</div>

<div class="center btn_block">
<% if user_signed_in? %>
  <% if @plan.user.id == current_user.id %>
      <%= link_to '編集', edit_plan_path(@plan), class: 'btn waves-effect waves-light' %>
      <%= link_to '削除', plan_path(@plan),method: :DELETE,data:{confirm: "「#{@plan.title}」を削除しますか？"}, class: 'btn waves-effect waves-light' %>

  <% end %>
<% end %>
<p>
  <% if @plan.image.url != nil %>
    <a href="<%= @plan.image %>" download="<%= @plan.title%>" class="btn waves-effect waves-light" id="download_link" target="_blank">ダウンロード</a>
  <% else %>
    <%= form_for(@plan,url: plan_path(@plan), remote: true) do |f| %>
      <%= f.hidden_field :id %>
      <%= f.submit "画像を生成", class: 'btn waves-effect waves-light',data: { disable_with: "画像生成中..." }%>
    <% end %>
  <% end %>
</p>
</div>


</section>

<script>
$(".pc_on").hide();
$(".sp").hide();
$(".sp_on").click(function(){
  $(".not_sp").hide();
  $(".sp").show();
  $(".sp_on").hide();
  $(".pc_on").show();
})

$(".pc_on").click(function(){
  $(".not_sp").show();
  $(".sp").hide();
  $(".sp_on").show();
  $(".pc_on").hide();
})
</script>