config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    member do
      post 'imgsave', to: 'plans#imgsave'
    end
  end


  # devise_for :users
  # devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users, controllers: {
    :omniauth_callbacks => "omniauth_callbacks",
    sessions:      'users/sessions'
  }

  # get 'users/show'
  get '/users/:username',to: 'users#show', as: 'users_show'
  #get '/users/:id',to: 'users#show', as: 'users_show'
  
  authenticated :user do
    root to: 'users#show'
  end

  root to:  'plans#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
  <nav class="nav-extended">
    <div class="nav-wrapper">
      <%= link_to 'LeanCanvasMaker', plans_path,class: 'brand-logo' %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to 'ホーム', plans_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to '描く',new_plan_path %></li>
        <li><%= link_to 'マイページ',users_show_path(current_user.username) %></li>
        <li><%= link_to '設定',edit_user_registration_path %></li>
        <% else %>
        <li><%= link_to '描く',new_user_session_path %></li>
        <li><%= link_to 'ログイン',new_user_session_path %></li>
        <% end %>

      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if user_signed_in? %>
        <li class="user_name">
          <%= link_to users_show_path(current_user.username) do %>
            <% if current_user.icon? %>
              <i><%= image_tag current_user.icon ,class: 'user_img_icon' if current_user.icon != nil %></i>
            <% else %>
              <i><%= image_tag current_user.image ,class: 'user_img_icon' if current_user.image != nil %></i>
            <% end %>
          <span><%= current_user.name %></span>
          <% end %>
        </li>
        <% end %>
        <li>
          <%= link_to plans_path do %>
            <i class="fas fa-home"></i>ホーム
          <% end %>
        </li>
        <% if user_signed_in? %>
        <li>
          <%= link_to new_plan_path do %>
            <i class="fas fa-pencil-alt"></i>描く
          <% end %>
          </li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fas fa-cogs"></i>設定
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to new_user_session_path do %>
            <i class="fas fa-pencil-alt"></i>描く
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <i class="fas fa-sign-in-alt"></i>ログイン
          <% end %>
        </li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <% if current_user.image.nil? && current_user.icon.nil? %>
          <%= link_to users_show_path(current_user.username), {:class => "user_icon right"} do %>
            <i class="material-icons">account_circle</i>
          <% end %>
        <% else %>
          <%= link_to users_show_path(current_user.username), {:class => "user_icon right"} do %>
            <% if current_user.icon? %>
              <i><%= image_tag current_user.icon ,class: 'user_img_icon' if current_user.icon != nil %></i>
            <% else %>
              <i><%= image_tag current_user.image ,class: 'user_img_icon' if current_user.image != nil %></i>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </nav>

<script type="text/javascript">
 $(".button-collapse").sideNav();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-KX4XMQ5');</script>
    <!-- End Google Tag Manager -->
    <%= csrf_meta_tags %>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '173346423319542',
      cookie     : true,
      xfbml      : true,
      version    : 'v2.12'
    });

    FB.AppEvents.logPageView();

  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KX4XMQ5"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <%= render 'layouts/header' %>
    <%= yield %>
    <div class="add_plan_block">
    <% if user_signed_in? %>
      <%= link_to new_plan_path, class: 'btn-floating btn-large waves-effect waves-light red' do %>
       <i class="material-icons">add</i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: 'btn-floating btn-large waves-effect waves-light red' do %>
       <i class="material-icons">add</i>
      <% end %>
    <% end %>
    </div>
    <footer>
      <div class="container">
        <a href="https://docs.google.com/forms/d/e/1FAIpQLScVXQo32Wh-nUK5fzSErwoFEKyoav0jh-Kv34MzP6mN8BHTIQ/viewform?usp=sf_link" class="white-text" target="_blank">
          お問い合わせ
        </a>
      </div>
      <div class="footer-copyright">
        <div class="container">
          © 2018 Copyright LeancanvasMaker 
         </div>
      </div>
    </footer>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.12&appId=173346423319542&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  </body>
</html>